colo:
  local_status: primary
  host_ip: 192.168.10.2
  host_user: ubuntu
  host_file_path: /home/ubuntu/colod/
  peer_ip: 192.168.10.3
  peer_user: ubuntu
  peer_file_path: /home/ubuntu/colod/
    

